### ISSUE TITLE
create general timeline

### ISSUE THREAD

**Issue by bbest** [mhk-env/mhk-env_shiny-apps#2]

**Comment by bbest** [comment]
Perhaps use [sequence diagrams in mermaid with DiagrammeR](https://rich-iannone.github.io/DiagrammeR/mermaid.html#sequence-diagrams) like:

![image](https://user-images.githubusercontent.com/2837257/100673540-792a9e80-3318-11eb-9bf2-19f9f2bebd0b.png)

We could derive min/mean/max between milestones of past [mhk-env projects](https://mhk-env.us/projects.html):

![image](https://user-images.githubusercontent.com/2837257/100673718-ca3a9280-3318-11eb-9015-ad164d4f0da8.png)

Could even be a bulleted list to start, ideally using R to pull from [MHK Project Timeline Input - Google Sheets](https://docs.google.com/spreadsheets/d/1HC5hXyi2RQSHevnV7rvyk748U5-X3iUw70ewHEfrHm0/edit#gid=793817660) similar to 
[projects.Rmd](https://github.com/mhk-env/mhk-env.github.io/blob/master/projects.Rmd).

**Comment by bbest** [comment]
Other ideas to consider for generating a timeline:

- Include required **comment periods** where the public is solicited for the opportunity to comment and the agency in charge must respond to all?
- What kinds of drop-down selections in the Shiny app do we want?
  * Technology
  * Range: min/mean/max
  * ... TBD

**Comment by bbest** [comment]
Even better is a [Gantt chart](https://mermaid-js.github.io/mermaid/#/gantt):
![image](https://user-images.githubusercontent.com/2837257/100677568-1ccb7d00-3320-11eb-9e0b-f19d1f96960a.png)

**Comment by Neil-Swanson** [comment]
This issue can be closed - generic timeline development has been replaced with using the 2020 PNNL roadmaps. @bbest
